In [3]:
print("NUMPY")
import numpy as np

NUMPY


In [40]:
import numpy as np

abc = np.array([
    [[[1, 2, 3], [4, 5, 6]],
     [[7, 8, 9], [10, 11, 12]]],
    
    [[[13, 14, 15], [16, 17, 18]],
     [[19, 20, 21], [22, 23, 24]]]
])

In [10]:
np.shape

(2, 2, 2, 3)

In [11]:
np.shape

(2, 2, 2, 3)

In [14]:
type(np)

numpy.ndarray

In [23]:
print(np.size(abc))

24


In [24]:
np.array([1,2,4],dtype=float)


array([1., 2., 4.])

In [25]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [38]:
np.arange(1,10,2).reshape(5,1)

array([[1],
       [3],
       [5],
       [7],
       [9]])

In [39]:
np.ones((3,4),dtype=int)
np.zeros((3,4),dtype=int)


array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [42]:
print("NUMPY")

NUMPY


In [43]:
np.random.random((5,4))

array([[0.92238535, 0.86599437, 0.71875697, 0.07443677],
       [0.13439486, 0.41245529, 0.60089784, 0.54554457],
       [0.27239378, 0.47321083, 0.34424851, 0.10502675],
       [0.75146716, 0.04220096, 0.63956724, 0.36664958],
       [0.82397295, 0.54202837, 0.30222928, 0.24075636]])

In [44]:
np.random.rand(3,4)

array([[0.29894277, 0.15612393, 0.13071224, 0.35207545],
       [0.20569678, 0.37560194, 0.20304133, 0.73974686],
       [0.44525942, 0.18722279, 0.52144278, 0.03141122]])

In [48]:
np.linspace(-100,10,10)

array([-100.        ,  -87.77777778,  -75.55555556,  -63.33333333,
        -51.11111111,  -38.88888889,  -26.66666667,  -14.44444444,
         -2.22222222,   10.        ])

In [49]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [50]:
a=np.array([1,2,3])
print(a)

[1 2 3]


In [51]:
np.array([1,2,3])

array([1, 2, 3])

In [8]:
np.arange(1,11).reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [12]:
#np.ones and np.zeros are used to create arrays of ones and zeros respectively. The shape of the array is specified as a tuple. For example, np.ones((3,4)) creates a 3x4 array of ones, and np.zeros((3,4)) creates a 3x4 array of zeros.
# np.ones((3,4),dtype=int)
np.zeros((3,4),dtype=int)


array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [13]:
#np.random.random((5,4))
np.random.rand(3,4)

array([[0.16470446, 0.48362729, 0.32246437, 0.49527197],
       [0.21659861, 0.06619723, 0.69066143, 0.04380468],
       [0.85749464, 0.84471432, 0.01847275, 0.06316196]])

In [14]:
# np.linspace explains how to create an array of evenly spaced numbers over a specified range. The function takes three arguments: the start value, the end value, and the number of samples to generate. For example, np.linspace(-100, 10, 10) generates an array of 10 evenly spaced numbers between -100 and 10.
np.linspace(-100, 10, 10)

array([-100.        ,  -87.77777778,  -75.55555556,  -63.33333333,
        -51.11111111,  -38.88888889,  -26.66666667,  -14.44444444,
         -2.22222222,   10.        ])

In [15]:
# np.identity creates a square identity matrix of the specified size. An identity matrix is a square matrix with ones on the main diagonal and zeros elsewhere. For example, np.identity(4) creates a 4x4 identity matrix.
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])